/**
 * PDF Report Generator for Startup Valuations
 * Uses jsPDF to generate a professional valuation summary
 */

import jsPDF from 'jspdf'
import { telemetry } from '../analytics/telemetry'

type ReportData = {
  companyName: string
  stage: string
  stageLabel: string
  createdAt: Date
  // Metrics
  arr: number
  monthlyGrowth: number
  tam: number
  grossMargin: number
  netRetention: number
  burnMultiple: number
  teamStrength: number
  differentiation: number
  // Valuations
  bear: number
  base: number
  bull: number
  revenueMultiple: number
  confidence: number
  // Insights
  insights: string[]
}

const formatCurrency = (value: number): string => {
  if (value >= 1_000_000_000) {
    return `$${(value / 1_000_000_000).toFixed(1)}B`
  }
  if (value >= 1_000_000) {
    return `$${(value / 1_000_000).toFixed(1)}M`
  }
  if (value >= 1_000) {
    return `$${(value / 1_000).toFixed(0)}K`
  }
  return `$${value.toFixed(0)}`
}

export function generateValuationReport(data: ReportData): void {
  const doc = new jsPDF()
  
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 20
  const contentWidth = pageWidth - margin * 2
  let yPosition = margin

  // Colors
  const primaryColor: [number, number, number] = [99, 102, 241]
  const textColor: [number, number, number] = [30, 41, 59]
  const mutedColor: [number, number, number] = [100, 116, 139]
  const bearColor: [number, number, number] = [255, 121, 189]
  const baseColor: [number, number, number] = [99, 102, 241]
  const bullColor: [number, number, number] = [52, 211, 153]

  // Helper functions
  const addText = (text: string, x: number, y: number, options?: { 
    fontSize?: number
    fontStyle?: 'normal' | 'bold'
    color?: [number, number, number]
    align?: 'left' | 'center' | 'right'
  }) => {
    const { fontSize = 10, fontStyle = 'normal', color = textColor, align = 'left' } = options || {}
    doc.setFontSize(fontSize)
    doc.setFont('helvetica', fontStyle)
    doc.setTextColor(...color)
    doc.text(text, x, y, { align })
  }

  const addLine = (y: number, color: [number, number, number] = [226, 232, 240]) => {
    doc.setDrawColor(...color)
    doc.setLineWidth(0.5)
    doc.line(margin, y, pageWidth - margin, y)
  }

  // --- Header ---
  addText('STARTUP VALUATION REPORT', pageWidth / 2, yPosition, {
    fontSize: 18,
    fontStyle: 'bold',
    color: primaryColor,
    align: 'center',
  })
  yPosition += 8
  
  addText('Generated by Startup Value Navigator', pageWidth / 2, yPosition, {
    fontSize: 10,
    color: mutedColor,
    align: 'center',
  })
  yPosition += 6
  
  addText(data.createdAt.toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  }), pageWidth / 2, yPosition, {
    fontSize: 9,
    color: mutedColor,
    align: 'center',
  })
  yPosition += 10
  
  addLine(yPosition)
  yPosition += 12

  // --- Company Info ---
  addText(data.companyName || 'Unnamed Company', margin, yPosition, {
    fontSize: 20,
    fontStyle: 'bold',
  })
  yPosition += 8
  
  addText(`${data.stageLabel} Stage`, margin, yPosition, {
    fontSize: 12,
    color: primaryColor,
  })
  yPosition += 15

  // --- Valuation Summary Box ---
  doc.setFillColor(248, 250, 252)
  doc.roundedRect(margin, yPosition - 5, contentWidth, 50, 4, 4, 'F')
  
  const boxCenterY = yPosition + 17
  const thirdWidth = contentWidth / 3
  
  // Bear
  addText('Bear Case', margin + thirdWidth / 2, boxCenterY - 8, {
    fontSize: 9,
    color: mutedColor,
    align: 'center',
  })
  addText(formatCurrency(data.bear), margin + thirdWidth / 2, boxCenterY + 4, {
    fontSize: 16,
    fontStyle: 'bold',
    color: bearColor,
    align: 'center',
  })
  
  // Base
  addText('Base Case', margin + thirdWidth + thirdWidth / 2, boxCenterY - 8, {
    fontSize: 9,
    color: mutedColor,
    align: 'center',
  })
  addText(formatCurrency(data.base), margin + thirdWidth + thirdWidth / 2, boxCenterY + 4, {
    fontSize: 18,
    fontStyle: 'bold',
    color: baseColor,
    align: 'center',
  })
  
  // Bull
  addText('Bull Case', margin + thirdWidth * 2 + thirdWidth / 2, boxCenterY - 8, {
    fontSize: 9,
    color: mutedColor,
    align: 'center',
  })
  addText(formatCurrency(data.bull), margin + thirdWidth * 2 + thirdWidth / 2, boxCenterY + 4, {
    fontSize: 16,
    fontStyle: 'bold',
    color: bullColor,
    align: 'center',
  })
  
  yPosition += 55

  // --- Key Metrics ---
  addText('KEY METRICS', margin, yPosition, {
    fontSize: 11,
    fontStyle: 'bold',
    color: primaryColor,
  })
  yPosition += 8
  
  const metrics = [
    ['Annual Recurring Revenue (ARR)', data.arr === 0 ? 'Pre-revenue' : `$${data.arr}M`],
    ['Monthly Growth Rate', `${data.monthlyGrowth}%`],
    ['Total Addressable Market (TAM)', `$${data.tam}B`],
    ['Gross Margin', `${data.grossMargin}%`],
    ['Net Revenue Retention', `${data.netRetention}%`],
    ['Burn Multiple', data.burnMultiple === 0 ? 'Profitable' : `${data.burnMultiple}x`],
    ['Revenue Multiple Applied', data.revenueMultiple > 0 ? `${data.revenueMultiple.toFixed(1)}x` : 'N/A'],
    ['Model Confidence', `${Math.round(data.confidence * 100)}%`],
  ]
  
  metrics.forEach(([label, value], index) => {
    const isEven = index % 2 === 0
    const xOffset = isEven ? margin : margin + contentWidth / 2
    const rowY = yPosition + Math.floor(index / 2) * 12
    
    addText(label, xOffset, rowY, { fontSize: 9, color: mutedColor })
    addText(value, xOffset + contentWidth / 2 - 10, rowY, { 
      fontSize: 10, 
      fontStyle: 'bold',
      align: 'right',
    })
  })
  
  yPosition += Math.ceil(metrics.length / 2) * 12 + 10

  // --- Qualitative Scores ---
  addLine(yPosition)
  yPosition += 10
  
  addText('QUALITATIVE FACTORS', margin, yPosition, {
    fontSize: 11,
    fontStyle: 'bold',
    color: primaryColor,
  })
  yPosition += 8
  
  addText('Team Strength', margin, yPosition, { fontSize: 9, color: mutedColor })
  addText(`${data.teamStrength.toFixed(1)} / 5`, margin + 80, yPosition, { fontSize: 10, fontStyle: 'bold' })
  
  addText('Product Moat / Defensibility', margin + contentWidth / 2, yPosition, { fontSize: 9, color: mutedColor })
  addText(`${data.differentiation.toFixed(1)} / 5`, margin + contentWidth / 2 + 100, yPosition, { fontSize: 10, fontStyle: 'bold' })
  
  yPosition += 15

  // --- Insights ---
  if (data.insights.length > 0) {
    addLine(yPosition)
    yPosition += 10
    
    addText('KEY INSIGHTS', margin, yPosition, {
      fontSize: 11,
      fontStyle: 'bold',
      color: primaryColor,
    })
    yPosition += 8
    
    data.insights.forEach((insight) => {
      // Clean up emojis for PDF
      const cleanInsight = insight
        .replace(/[✅⚠️]/g, '•')
        .trim()
      
      const lines = doc.splitTextToSize(cleanInsight, contentWidth - 10)
      doc.setFontSize(9)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(...textColor)
      
      lines.forEach((line: string) => {
        if (yPosition > 270) {
          doc.addPage()
          yPosition = margin
        }
        doc.text(line, margin + 5, yPosition)
        yPosition += 5
      })
      yPosition += 4
    })
  }

  // --- Disclaimer ---
  if (yPosition > 240) {
    doc.addPage()
    yPosition = margin
  }
  
  yPosition = Math.max(yPosition + 10, 250)
  addLine(yPosition)
  yPosition += 8
  
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(251, 191, 36)
  doc.text('DISCLAIMER', margin, yPosition)
  yPosition += 5
  
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100, 116, 139)
  const disclaimer = 'This valuation report is a directional estimate based on user inputs and typical startup valuation heuristics. ' +
    'It is NOT a formal valuation, fairness opinion, or tax/legal advice. This document should not be relied upon for ' +
    'investment decisions. Always consult qualified professionals (CPAs, attorneys, investment bankers) for formal valuations ' +
    'and important financial decisions.'
  
  const disclaimerLines = doc.splitTextToSize(disclaimer, contentWidth)
  disclaimerLines.forEach((line: string) => {
    doc.text(line, margin, yPosition)
    yPosition += 4
  })

  // --- Footer ---
  yPosition = doc.internal.pageSize.getHeight() - 10
  addText('Generated by Startup Value Navigator • startupvaluator.io', pageWidth / 2, yPosition, {
    fontSize: 8,
    color: mutedColor,
    align: 'center',
  })

  // Save the PDF
  const fileName = `${(data.companyName || 'valuation').replace(/[^a-zA-Z0-9]/g, '_')}_Valuation_Report.pdf`
  doc.save(fileName)
  
  telemetry.track('report_downloaded', {})
}

